name: Build-depoly-Vite-react

on: 
  push:
      branches:
        - finch_vite
  workflow_dispatch:
jobs:
  Build-Vite: 
    name: complile production build 
    runs-on: ubuntu-latest
    env:
      CI : ""
    defaults:
    
      run: 
        working-directory: ./dev
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: check work dir
        run: pwd 
      - name: setup nodejs 
        uses: actions/setup-node@v3
        with :
           node-version: 16
      - name: install node dependencies 
        run: npm install
      - name: run craco build
        run: npm run build
      - name: rename main.js to main.txt
        run:  mv ./build/static/js/main.js ./build/static/js/main.txt

      - name: edit index.html
        run: > 
          rm -rf ./build/index.html ; 
          echo '
          <!doctype html>
          <html lang="en">

          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width,initial-scale=1" />
            <meta name="theme-color" content="#000000" />
            <title>Finch</title>
            <link href="./static/css/main.css" rel="stylesheet">

            <script type="text/javascript">
              const fullUrl = window.location.origin + window.location.pathname;
              const fileUrl = fullUrl.slice(0, fullUrl.lastIndexOf("/"))
              const txtUrl = fileUrl + "/static/js/";

              function loadWords(filename, asynch) {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function () {
                  if (this.readyState == 4 && this.status == 200) {
                    var sTag = document.createElement("script");
                    sTag.type = "module";
                    sTag.innerHTML = this.responseText;
                    var head = document.getElementsByTagName("head")[0];
                    head.appendChild(sTag);
                  }
                };
                var url = txtUrl + filename + ".txt";
                xhr.open("GET", url, asynch);
                xhr.send();
              }

              loadWords("main", true)
            </script>
          </head>

          <body><noscript>You need to enable JavaScript to run this app.</noscript>
            <div id="root"></div>
          </body>

          </html>' >> ./build/index.html
      - name: upload build to artifacts for production 
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: ./dev/build/
          retention-days: 1

      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
  Upload-prod-build:
    name: upload production build to google drive
    needs: Build-Vite
    runs-on: ubuntu-latest
    steps:
      - name: download production build artifacts
        uses: actions/download-artifact@v3
        with:
         name: production-build
    
      - name: Check structure of downloaded files
        run: ls -R
 
      - name: Zip production build files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r finch-build-vite.zip *
          
      - name: check dir
        run:  ls -a
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "finch-build-vite.zip"
          overwrite: "true"
          folderId: ${{ secrets.folderId }}


 


